### ISSUE TITLE
Invalid protobuf message: expected bytes, bytearray found

### ISSUE THREAD

**Issue by BrentVerhaegen** [esphome/aioesphomeapi#358]
Was building a new version of my Docker container that is using the ESPHome API.
Upon building, the following error gets raised. This error wasn't there before, and the changes I made to my container are unrelated to the ESPHome part, so I believe something got broken recently in the API package

```
energy-meter-1.local: Connection error occurred: Invalid protobuf message: expected bytes, bytearray found
Fatal error: protocol.data_received() call failed.
protocol: <aioesphomeapi._frame_helper.APIPlaintextFrameHelper object at 0x7f6fedd8bb50>
transport: <_SelectorSocketTransport closing fd=6 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 876, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/_frame_helper.py", line 195, in data_received
    self._callback_packet(msg_type_int, packet_data)
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/_frame_helper.py", line 110, in _callback_packet
    self._on_pkt(Packet(type_, data))
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 581, in _process_packet
    msg.ParseFromString(pkt.data)
TypeError: expected bytes, bytearray found
```

The ESPHome device is and ESP32 and is running on ESPHome 2022.12.3 FW

Let me know if you need any debugging or more information

**Comment by bdraco** [comment]
Which version of protobuf do you have installed?

**Comment by BrentVerhaegen** [comment]
Protobuf verion 4.21.12
The one that comes with aioesphomeapi when installing it with pip3

Here are all my packages and their version in the container
```
aioesphomeapi==13.0.3
async-timeout==4.0.2
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.1.1
cryptography==39.0.0
idna==3.4
ifaddr==0.2.0
noiseprotocol==0.3.1
protobuf==4.21.12
pycparser==2.21
pymodbus==3.0.2
requests==2.28.1
urllib3==1.26.13
zeroconf==0.47.1
```

**Comment by bdraco** [comment]
I have `4.21.11`. Will try upgrading and see if I can repro

**Comment by bdraco** [comment]
No luck there. Works as expected for me.

**Comment by bdraco** [comment]
Tried it with `pip3 install --upgrade protobuf --force  --no-binary protobuf` as well to see if its a difference between the CPP version and pure python version but no error there either

**Comment by BrentVerhaegen** [comment]
I just tried with older protobuf version, and that doesn't fix the issue that I'm seeing.
But going back to an older version of aioesphomeapi does seem to fix the problem.
aioesphomeapi 13.0.3 seems to be causing this above error, but aioesphomeapi 13.0.2 is working fine

**Comment by bdraco** [comment]
Its going to be a `bytearray` in 13.0.3 and not `bytes` but the question is why does `ParseFromString` reject `bytearray` for you and not for all the systems I have

**Comment by BrentVerhaegen** [comment]
Which Python version are you running? The above error was thrown on Python 3.10
I just also tried building my container with Python 3.8, and that doesn't seem to throw the error

**Comment by bdraco** [comment]
```
 % python3 --version
Python 3.10.9
```

**Comment by BrentVerhaegen** [comment]
Hmm exactly same version on my end..
Could it be that I'm transfering some different data over the API than you are when testing? 

Here's a print of my states (got this by running the package with Python 3.8)
```
SensorState(key=2570682737, state=230.9199981689453, missing_state=False)
SensorState(key=3828357211, state=2.5989999771118164, missing_state=False)
SensorState(key=3466149700, state=405.5155029296875, missing_state=False)
SensorState(key=3585249587, state=-374.56927490234375, missing_state=False)
SensorState(key=2172363707, state=0.6800000071525574, missing_state=False)
SensorState(key=1992360424, state=9.637499809265137, missing_state=False)
SensorState(key=1676516688, state=231.41000366210938, missing_state=False)
SensorState(key=526413636, state=0.5830000042915344, missing_state=False)
SensorState(key=1410217821, state=0.0, missing_state=False)
SensorState(key=132170822, state=132.9529571533203, missing_state=False)
SensorState(key=1504929902, state=0.06400000303983688, missing_state=False)
SensorState(key=1696642093, state=0.20000000298023224, missing_state=False)
SensorState(key=1304792374, state=50.0, missing_state=False)
SensorState(key=360563053, state=22.0, missing_state=False)
SensorState(key=3436923411, state=42.95100021362305, missing_state=False)
SensorState(key=8661968, state=-64.0, missing_state=False)
SensorState(key=2689840309, state=-61.187461853027344, missing_state=False)
SensorState(key=1677001713, state=nan, missing_state=True)
SensorState(key=2254133052, state=nan, missing_state=True)
SensorState(key=688182462, state=nan, missing_state=True)
SensorState(key=3983408003, state=nan, missing_state=True)
SensorState(key=1616262030, state=nan, missing_state=True)
SensorState(key=1356779840, state=nan, missing_state=True)
SensorState(key=2689840309, state=-61.20623016357422, missing_state=False)
SensorState(key=1353830729, state=nan, missing_state=True)
SensorState(key=730850122, state=nan, missing_state=True)
SensorState(key=1265174127, state=nan, missing_state=True)
SensorState(key=3874755615, state=nan, missing_state=True)
SensorState(key=1618858790, state=nan, missing_state=True)
SensorState(key=4132396052, state=nan, missing_state=True)
SensorState(key=1095556293, state=nan, missing_state=True)
SensorState(key=2640694552, state=nan, missing_state=True)
SensorState(key=2248863234, state=nan, missing_state=True)
SensorState(key=3825237687, state=nan, missing_state=True)
SensorState(key=3552992144, state=nan, missing_state=True)
SensorState(key=3013548629, state=nan, missing_state=True)
SensorState(key=2570682737, state=230.63999938964844, missing_state=False)
SensorState(key=1676516688, state=231.07000732421875, missing_state=False)
SensorState(key=3828357211, state=2.572999954223633, missing_state=False)
SensorState(key=526413636, state=0.5830000042915344, missing_state=False)
SensorState(key=3466149700, state=400.3203125, missing_state=False)
SensorState(key=1410217821, state=0.0, missing_state=False)
SensorState(key=3585249587, state=-373.8636779785156, missing_state=False)
SensorState(key=132170822, state=132.78367614746094, missing_state=False)
SensorState(key=2172363707, state=0.6769999861717224, missing_state=False)
SensorState(key=1504929902, state=0.06400000303983688, missing_state=False)
SensorState(key=1992360424, state=10.762499809265137, missing_state=False)
SensorState(key=1696642093, state=0.22499999403953552, missing_state=False)
SensorState(key=1304792374, state=49.9900016784668, missing_state=False)
SensorState(key=360563053, state=22.0, missing_state=False)
SensorState(key=3436923411, state=102.9489974975586, missing_state=False)
SensorState(key=2570682737, state=230.89999389648438, missing_state=False)
SensorState(key=1676516688, state=231.25, missing_state=False)
SensorState(key=3828357211, state=2.5739998817443848, missing_state=False)
SensorState(key=526413636, state=0.5830000042915344, missing_state=False)
SensorState(key=3466149700, state=399.7823791503906, missing_state=False)
SensorState(key=1410217821, state=0.0, missing_state=False)
SensorState(key=3585249587, state=-372.1513366699219, missing_state=False)
SensorState(key=132170822, state=132.8371124267578, missing_state=False)
SensorState(key=2172363707, state=0.6729999780654907, missing_state=False)
SensorState(key=1504929902, state=0.06400000303983688, missing_state=False)
SensorState(key=1992360424, state=11.887499809265137, missing_state=False)
SensorState(key=1696642093, state=0.25, missing_state=False)
SensorState(key=1304792374, state=49.9900016784668, missing_state=False)
SensorState(key=360563053, state=22.0, missing_state=False)
SensorState(key=2570682737, state=230.7899932861328, missing_state=False)
SensorState(key=1676516688, state=231.2100067138672, missing_state=False)
SensorState(key=3828357211, state=2.572000026702881, missing_state=False)
SensorState(key=526413636, state=0.5830000042915344, missing_state=False)
SensorState(key=3466149700, state=400.3977355957031, missing_state=False)
SensorState(key=1410217821, state=0.0, missing_state=False)
SensorState(key=3585249587, state=-373.504638671875, missing_state=False)
SensorState(key=132170822, state=132.94879150390625, missing_state=False)
SensorState(key=2172363707, state=0.6759999990463257, missing_state=False)
SensorState(key=1504929902, state=0.06400000303983688, missing_state=False)
SensorState(key=1992360424, state=13.006250381469727, missing_state=False)
SensorState(key=1696642093, state=0.2718749940395355, missing_state=False)
SensorState(key=1304792374, state=50.0, missing_state=False)
SensorState(key=360563053, state=22.0, missing_state=False)
SensorState(key=8661968, state=-63.0, missing_state=False)
SensorState(key=2570682737, state=230.33999633789062, missing_state=False)
SensorState(key=1676516688, state=230.50999450683594, missing_state=False)
SensorState(key=3828357211, state=2.575000047683716, missing_state=False)
SensorState(key=526413636, state=0.5820000171661377, missing_state=False)
SensorState(key=3466149700, state=398.6566162109375, missing_state=False)
SensorState(key=1410217821, state=0.0, missing_state=False)
SensorState(key=3585249587, state=-373.7942199707031, missing_state=False)
SensorState(key=132170822, state=132.28927612304688, missing_state=False)
SensorState(key=2172363707, state=0.6740000247955322, missing_state=False)
SensorState(key=1504929902, state=0.06499999761581421, missing_state=False)
SensorState(key=1992360424, state=14.121874809265137, missing_state=False)
SensorState(key=1696642093, state=0.296875, missing_state=False)
SensorState(key=1304792374, state=49.9900016784668, missing_state=False)
SensorState(key=360563053, state=22.0, missing_state=False)
SensorState(key=2570682737, state=230.97000122070312, missing_state=False)
SensorState(key=1676516688, state=231.35000610351562, missing_state=False)
SensorState(key=3828357211, state=2.5880000591278076, missing_state=False)
SensorState(key=526413636, state=0.5830000042915344, missing_state=False)
SensorState(key=3466149700, state=403.00927734375, missing_state=False)
SensorState(key=1410217821, state=0.0, missing_state=False)
SensorState(key=3585249587, state=-375.0556640625, missing_state=False)
SensorState(key=132170822, state=133.15423583984375, missing_state=False)
SensorState(key=2172363707, state=0.6740000247955322, missing_state=False)
SensorState(key=1504929902, state=0.06400000303983688, missing_state=False)
SensorState(key=1992360424, state=15.237500190734863, missing_state=False)
SensorState(key=1696642093, state=0.3187499940395355, missing_state=False)
SensorState(key=1304792374, state=50.0, missing_state=False)
SensorState(key=360563053, state=22.0, missing_state=False)
SensorState(key=2570682737, state=230.85000610351562, missing_state=False)
SensorState(key=1676516688, state=231.30999755859375, missing_state=False)
SensorState(key=3828357211, state=2.5869998931884766, missing_state=False)
SensorState(key=526413636, state=0.5830000042915344, missing_state=False)
SensorState(key=3466149700, state=402.2630310058594, missing_state=False)
SensorState(key=1410217821, state=0.0, missing_state=False)
SensorState(key=3585249587, state=-374.6534423828125, missing_state=False)
SensorState(key=132170822, state=132.86720275878906, missing_state=False)
SensorState(key=2172363707, state=0.675000011920929, missing_state=False)
SensorState(key=1504929902, state=0.06400000303983688, missing_state=False)
SensorState(key=1992360424, state=16.356250762939453, missing_state=False)
SensorState(key=1696642093, state=0.34375, missing_state=False)
SensorState(key=1304792374, state=50.0, missing_state=False)
SensorState(key=360563053, state=22.0, missing_state=False)
```

Does this help you in any way? Can I provide some other data?

**Comment by bdraco** [comment]
I'll adjust the exception to provide more information

**Comment by bdraco** [comment]
Well I wrote a test for this and it passes locally but just failed the CI so some progress

https://github.com/esphome/aioesphomeapi/pull/359

**Comment by bdraco** [comment]
I'd really like to avoid the overhead of converting `bytearray` to `bytes` so I'm still working on a fix

**Comment by bdraco** [comment]
I guess we are stuck with the type conversion overhead. I can't find a way around it or figure out why it doesn't affect my systems.

**Comment by bdraco** [comment]
I just pushed 13.0.4 which should fix the issue.  Thanks for the report.
